### ISSUE TITLE
Привет, Хауди Хо)

### ISSUE THREAD

**Issue by Egor228000** [Priler/jarvis#1]
У меня проблема в кешей 2.0. Скопировал код как у тебя, всё в точь точь, запускаю файл main.py и выдаёт бесконечно input overflow ![Снимок экрана от 2023-02-05 22-53-25](https://user-images.githubusercontent.com/118193031/216830001-581045c2-bd87-40b2-b083-29369ebfb413.png). Когда я останавливаю программу с помощью комбинаций Ctrl + c то у меня появляется такая ошибка 
![image](https://user-images.githubusercontent.com/118193031/216830038-5ad734a2-a017-46f7-b0f9-f8e944169eff.png)

Помогите пожалуйста))))))

**Comment by nicolaepostica** [comment]
Там просто не обработан ивент принудительно завершения работы

`try:
    # DO THINGS
except KeyboardInterrupt:
    # quit
    sys.exit()`

[источник](https://stackoverflow.com/questions/15318208/capture-control-c-in-python)
