### ISSUE TITLE
NC license is non-free

### ISSUE THREAD

**Issue by TechnologyClassroom** [Priler/jarvis#109]
Non-commercial (NC) clauses are non-free as they are not free software according to the [FSF](https://www.gnu.org/philosophy/free-sw.html#selling), open source according to the [OSI](https://opensource.org/osd#free-redistribution), or free culture according to [Freedom Defined](https://freedomdefined.org/Definition). 

I would recommend using CC-BY-SA-4.0 or CC-BY-4.0 instead which are free culture Creative Commons licenses. An FSF or OSI approved license would also work and might be more appropriate for this project.

**Comment by erritis** [comment]
I think it's obvious that he did it on purpose and hopes to sell this project to those who can make a commercial product based on this solution. For example, to those who will start selling a smart speaker based on a rasberry pi and a custom case in the form of an iron man helmet. But maybe I'm wrong.

**Comment by Priler** [comment]
The NC clause was applied on purpose. This project cannot be used for any commercial purpose (at least for now). I see no reason why it should be changed.

**Comment by TechnologyClassroom** [comment]
That is a choice you can make, but it results in this project being a dead end. Further development typically is limited to the owner.

The 9th line of the README.md file states "[Open source (full transparency)](https://github.com/Priler/jarvis/blob/master/README.md?plain=1#L9)" so that should be changed. NC would make the project [source-available](https://en.wikipedia.org/wiki/Source_available).
