### ISSUE TITLE
Проблема с PORCUPINE

### ISSUE THREAD

**Issue by SonJUS** [Priler/jarvis#11]
При запуске Main.py выдают ошибку. Не знаю как решить.
File "main.py", line 54, in <module>
    porcupine = pvporcupine.create(
  File "C:\Users\ПК\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\__init__.py", line 77, in create
    return Porcupine(
  File "C:\Users\ПК\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\porcupine.py", line 158, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine.porcupine.PorcupineIOError

**Comment by Kanorto** [comment]
У тебя не возникало ошибок во время установки зависимостей?

**Comment by SonJUS** [comment]
Не возникало

**Comment by Kanorto** [comment]
Иногда после неверной установки не пишет ошибку, так как она завершена до конца. Открой консоль и пролистал выполнение всей команды по установке зависимостей

**Comment by SonJUS** [comment]
Я уже несколько раз переустановил, ничего не помогло

**Comment by Kanorto** [comment]
решилась как-то?

**Comment by SonJUS** [comment]
нет

**Comment by Priler** [comment]
Ошибка, вероятно, связана с настройками безопасности Windows.
Подробности тут https://github.com/Picovoice/porcupine/issues/617
