### ISSUE TITLE
Проблема с компиляцией.

### ISSUE THREAD

**Issue by LonelyGR** [Priler/jarvis#121]
Из-за ошибок показанные в скриншотах, компиляция не выполняется.
![photo_2024-04-02_18-32-27](https://github.com/Priler/jarvis/assets/165814746/557ec6a0-3007-4ca7-a942-06a6fe9709c1)
![image](https://github.com/Priler/jarvis/assets/165814746/dacdb3b5-d666-48a4-8e22-809b1dd23f8d)

И файлов с такими ошибками 14

**Comment by ilyamixaltik** [comment]
Не установлены зависимости (библиотеки), которые использовались про разработке. Установка идёт командой "npm install". Это команда для установки зависимостей
