### ISSUE TITLE
с введенного голосом текста сделать аргумент

### ISSUE THREAD

**Issue by Ilya987** [Priler/jarvis#131]
обучаю джарвиса новым вещам и для многого необходимо текст расшифрованный с помощью нейросети преобразовать в аргумент
к примеру хочу сделать чтобы джарвис мог искать в поисковике 
- Джарвис, найди(команда) тутор от Хауди (аргумент)
AHK:
![изображение_2024-07-08_195337974](https://github.com/Priler/jarvis/assets/72878508/920e3f10-5509-49c6-a7d1-1e0bc2e0807d)

**Comment by Priler** [comment]
В новой версии это будет, жди.
