### ISSUE TITLE
Когда Chat GPT? Когда NLU? Проект заброшен?

### ISSUE THREAD

**Issue by Savely22828** [Priler/jarvis#134]
Так-как в репозитории отключены дискуссии придётся писать здесь.
Последнее видео про Джарвиса было 4 с хреном месяца назад, ChatGPT всё ещё не добавлен, НИЧЕГО ИЗ ПУНКТА Text-to-Speech не добавлено в проект! Vosk медленный и не отвечает,, при использовании Rustpotter он вообще не отвечает, а в Picovoice зарегистрироваться невозможно так-как там нужен eMail компании. Про ChatGPT я лучше промолчу. И я бы понял если бы вы готовили обновление, но никому об этом не говорили, а на GitHub появлялись бы коммиты, но нет, последний коммит был хрен пойми когда. Итог: проект сдох.

**Comment by Artem777g** [comment]
Согласен,но а вообще-то здесь https://github.com/hhy5277/jarvis-3?ysclid=m0g5hj3xan939601668 написано что  это обновление версии Джарвиса только я не понимаю как обновить старую версию Джарвиса

**Comment by Savely22828** [comment]
> Согласен,но а вообще-то здесь https://github.com/hhy5277/jarvis-3?ysclid=m0g5hj3xan939601668 написано что это обновление версии Джарвиса только я не понимаю как обновить старую версию Джарвиса

Кстати, может создать свой репозиторий как ребут проекта (долго не отвечал, ноут был в ремонте).

**Comment by Priler** [comment]
Проект не сдох, у меня не хватает времени активно его пилить.
Коммиты не делаются, тк нет смысла пушить куски нерабочего полностью кода.
Текущий билд на ГХ работает и компилится, если разобраться.

Дальше будет версия 0.1.0, возможно я расширю инструкции по сборке.
Важно помнить, что это экспериментальный проект, разрабатываемый всего одним человеком в свободное время.
