### ISSUE TITLE
При запуске  Current system is not supported.

### ISSUE THREAD

**Issue by Matvel007** [Priler/jarvis#15]
![image](https://user-images.githubusercontent.com/73697266/232313922-7b9e6730-e97d-449e-aeb4-f09c83b42ed9.png)

**Comment by dimitrieidifesk** [comment]
Предположу, что с версии Python что то не то. У самого возникала такая ошибка при попытке запустить на 3.10

**Comment by nikolay59088** [comment]
![image](https://user-images.githubusercontent.com/36686958/232314607-53a501f3-66a2-44b9-805e-bbdc19697a1b.png)
тут же написано, переустанови python-levenshtain

**Comment by Matvel007** [comment]
> ![изображение](https://user-images.githubusercontent.com/36686958/232314607-53a501f3-66a2-44b9-805e-bbdc19697a1b.png) тут же написано, переустанови python-levenshtein. P.S. Поставил Python 3.11. Вылезла такая же ошибка. После переустановки у меня ошибка ушла.

Переустановил, точно ткая же ошибка но с PvRecorder. И у меня 3.8.3 установлен.

**Comment by Matvel007** [comment]
![image](https://user-images.githubusercontent.com/73697266/232315796-089dd680-95e4-4f9c-8e57-ed93831ca419.png)

**Comment by nikolay59088** [comment]
а какая windows у тебя стоит и какой разрядности?

**Comment by Matvel007** [comment]
> а какая windows у тебя стоит и какой разрядности? просто насколько вижу в информации, pvrecorder работает только 64 битной системе ![изображение](https://user-images.githubusercontent.com/36686958/232321829-c344b0ea-afa1-4a12-88dd-6e2dab5b501d.png)

11 винда 64 бит

**Comment by nikolay59088** [comment]
удалось воспроизвести твою ошибку) 
![image](https://user-images.githubusercontent.com/36686958/232479056-13b3617f-9919-4dd1-a3e0-1c5cb0149884.png)
В общем нужно переустановить python на 64 разрядный, у тебя сейчас 32 разрядный (по пути увидел это и мысль появилась)

**Comment by Priler** [comment]
[pvrecorder ](https://pypi.org/project/pvrecorder/) работает только с Windows (amd64).
То есть нужна 64 битная версия Python и самой винды, соответственно.
Для работы на x32 нужно переписать код с использованием другой библиотеки для записи звука.
