### ISSUE TITLE
Распознавание названия приложений

### ISSUE THREAD

**Issue by Harlnezumi** [Priler/jarvis#153]
Всем привет, я сейчас пишу свой проект используя англ. модель VOSK. Однако, я обнаружил, что модель не знает названия некоторых приложений (RimWorld, Dota итд), я пытался найти как добавить новые слова в VOSK, но я не совсем разобрался как это осуществить. Может, кто знает как? Буду очень благодарен!

**Comment by Kamichy** [comment]
Напиши мне в телеграмм @alex_gold_ua, помогу, чем смогу.

**Comment by Kamichy** [comment]
Напиши мне в телеграмм @alex_gold_ua, помогу, чем смогу.

**Comment by Harlnezumi** [comment]
А, спасибо, сам уже понял как
