### ISSUE TITLE
Проблема с tts

### ISSUE THREAD

**Issue by ZersonNorell** [Priler/jarvis#16]
запускаю джарвиса через терминал - ничего не происходит, при дебаге обнаружил вот такую проблему

Exception has occurred: OSError
[WinError 6] Неверный дескриптор
  File "G:\jarvis-master\tts.py", line 15, in <module>
    model, _ = torch.hub.load(repo_or_dir='snakers4/silero-models',
OSError: [WinError 6] Неверный дескриптор

**Comment by Kanorto** [comment]
ты не даешь полной ошибки. Скорее всего папка твоего пользователя называется по русски, что мешает установке.
Вот тут есть инструкция для подобных случаев
https://github.com/Priler/jarvis/issues/14#issuecomment-1510380432
