### ISSUE TITLE
Ошибка pvporcupine._porcupine.PorcupineIOError

### ISSUE THREAD

**Issue by MaksimSergin** [Priler/jarvis#18]
При запуске Джарвиса вылетает ошибка:

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    porcupine = pvporcupine.create(
  File "C:\jarvis-master\venv\lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\jarvis-master\venv\lib\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineIOError

У кого-нибудь есть какие-нибудь предложения по фиксу?

**Comment by harchock** [comment]
у меня у самого такая ошибка.
единственное что я смог сделать на 46 строке поменять код на 
`porcupine = pvporcupine.create(
    access_key=config.environ.get('PICOVOICE_TOKEN'),
    keywords=['jarvis'],
    sensitivities=[1]
)
`
и выдавало уже другую ошибку
`C:\Users\Михаил\Desktop\jarvis-master>python main.py
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    config.environ.get('PICOVOICE_TOKEN'),
AttributeError: module 'config' has no attribute 'environ'`
если решишь эту ошибку то отпиши мне верный код плииз

**Comment by MrWinamp** [comment]
нужно в файл dev.env добавить токены с сайта openai и picovoice

**Comment by MaksimSergin** [comment]
> нужно в файл dev.env добавить токены с сайта openai и picovoice

Уже добавлены, ошибка вроде как не связана с токенами, иначе была бы ошибка: `pvporcupine.porcupine.PorcupineInvalidArgumentError` или `ValueError: access_key should be a non-empty string.`

**Comment by MrWinamp** [comment]
Хмм, тогда странно. Ну проверьте на всякий случай все ли модули из requirements установлены. Потому что помню тоже об это запинался, хотя не всегда явно на ошибку импорта указывало, плюс после добавления токенов в dev.env (эти угловые скобки тоже надо удалить в поле для токена) у меня код отработал до 277 строки, пока как обойти дальше сам хз.

**Comment by Kanorto** [comment]
> C:\Users\Михаил\Desktop\jarvis-master>python main.py Traceback (most recent call last): File "main.py", line 48, in <module> config.environ.get('PICOVOICE_TOKEN'), AttributeError: module 'config' has no attribute 'environ'

Так у тебя ошибка именно из-за этой смены строки. Прочитай ошибку внимательно. На 48 строке у тебя рассказано что в конфиге нет параметра environ

**Comment by Kanorto** [comment]
Еще с версии 2.0.4 происходит такая ошибка. Разработчики дали небольшой костыль, но это возможно не поможет. По крайней мере вы можете попытаться прочитать то что там написано.
https://github.com/Picovoice/porcupine/issues/617

**Comment by Priler** [comment]
Ошибка, вероятно, связана с настройками безопасности Windows.
Подробности тут https://github.com/Picovoice/porcupine/issues/617

**Comment by belnek** [comment]
Изменение политики по 617 посту не помогло. Продолжает вылезать PorcupineIOError

**Comment by Kanorto** [comment]
> Ошибка, вероятно, связана с настройками безопасности Windows. Подробности тут [Picovoice/porcupine#617](https://github.com/Picovoice/porcupine/issues/617)

Мне если что тоже не помогло

**Comment by MaksimSergin** [comment]
https://github.com/Picovoice/porcupine/issues/947
Ошибку сейчас фиксят

**Comment by Kanorto** [comment]
Я знаю. Я тот тикет открыл

**Comment by Kanorto** [comment]
Открой обратно этот топик
