### ISSUE TITLE
Ошибочка

### ISSUE THREAD

**Issue by mynameisdavis** [Priler/jarvis#19]
Настроил в файле config.py, установил модули, запускаю main.py, проходит 3 секунды и  ошибка
![Screenshot_3](https://user-images.githubusercontent.com/101875041/232435523-d46b0d1b-e3e4-4299-9da8-850514229c03.png)

**Comment by harchock** [comment]
оно говорит что якобы ты не ввёл код
хотя у меня та же самая ошибка и я не могу её исправить

**Comment by Kanorto** [comment]
Еще с версии 2.0.4 происходит такая ошибка. Разработчики дали небольшой костыль, но это возможно не поможет. По крайней мере вы можете попытаться прочитать то что там написано.
https://github.com/Picovoice/porcupine/issues/617

**Comment by SpecialDigital** [comment]
Попробуйте напрямую указать в файле config.py ключи:
![image](https://user-images.githubusercontent.com/131171036/232791599-75062f8a-42e7-4372-80f7-9babd874857a.png)
