### ISSUE TITLE
помогите с проблемкой

### ISSUE THREAD

**Issue by harchock** [Priler/jarvis#21]
C:\Users\Михаил\Desktop\jarvis-master>python main.py Traceback (most recent call last): File "main.py", line 46, in <module> porcupine = pvporcupine.create( File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\_factory.py", line 69, in create return Porcupine( File "C:\Users\Михаил\AppData\Local\Programs\Python\Python38\lib\site-packages\pvporcupine\_porcupine.py", line 123, in __init__ raise ValueError("access_key should be a non-empty string.") ValueError: access_key should be a non-empty string.

сама ошибка
я делал всё по инструкции
API в dev.env я ввёл
не помогло

**Comment by MaksimSergin** [comment]
Скопи пасть сюда config.py (токен обрежь)

**Comment by harchock** [comment]
`from dotenv import load_dotenv
import os

# Find .env file with os variables
load_dotenv("dev.env")

# Конфигурация
VA_NAME = 'Jarvis'
VA_VER = "3.0"
VA_ALIAS = ('джарвис',)
VA_TBR = ('скажи', 'покажи', 'ответь', 'произнеси', 'расскажи', 'сколько', 'слушай')

# ID микрофона (можете просто менять ID пока при запуске не отобразится нужный)
# -1 это стандартное записывающее устройство
MICROPHONE_INDEX = -1

# Путь к браузеру Google Chrome
CHROME_PATH = 'C:\Program Files\Google\Chrome\Application\chrome.exe %s'`

**Comment by harchock** [comment]
если не сложно напиши мне в телеграмм @m_ll_n_r
может так будет легче

**Comment by Kanorto** [comment]
Еще с версии 2.0.4 происходит такая ошибка. Разработчики дали небольшой костыль, но это возможно не поможет. По крайней мере вы можете попытаться прочитать то что там написано.
https://github.com/Picovoice/porcupine/issues/617

**Comment by Kanorto** [comment]
ты не ввел токен PICOVOICE_TOKEN

**Comment by SpecialDigital** [comment]
Была такая же проблема. Сильно не заморачивался, просто указал в config.ру токены
 # Токен Picovoice
PICOVOICE_TOKEN = os.getenv('твой токен')

# Токен OpenAI
OPENAI_TOKEN = os.getenv('твой токен')

Но теперь столкнулся с проблемой с озвучкой текста:
[WARN] Overflow - reader is not reading fast enough.

**Comment by harchock** [comment]
> 

у меня указан токен, я попробовал убрать и сам дотенв не помогло
проблема в самом плагине скорее всего
