### ISSUE TITLE
Помогите пожалуйста

### ISSUE THREAD

**Issue by ligets** [Priler/jarvis#22]
![image](https://user-images.githubusercontent.com/131186952/233095666-069e2c16-8972-4d2b-bead-e1b6235b6000.png)
При запуске выдаёт ошибку, были обсуждения как это решить, сделал как там говорили ничего не помогло.

**Comment by Kanorto** [comment]
https://github.com/Priler/jarvis/issues/14#issuecomment-1510380432
Решение тут

**Comment by ligets** [comment]
Теперь выдаёт другую ошибку.
![image](https://user-images.githubusercontent.com/131186952/233138099-b177d0c3-fe7f-4ccc-8d75-64e106a688bc.png)
