### ISSUE TITLE
Проблема с нейросетью

### ISSUE THREAD

**Issue by scarabhub** [Priler/jarvis#24]
Приветствую, я смог запустить джарвиса, но к сожалению не работает Openai. Джарвис отвечает только на кастомные команды

**Comment by Priler** [comment]
Возможно не прописаны API ключи или взяты чьи-то ключи (с достигнутым лимитом).
Предоставь текст ошибки.

**Comment by scarabhub** [comment]
> Возможно не прописаны API ключи или взяты чьи-то ключи (с достигнутым лимитом). Предоставь текст ошибки.

Весь момент в том, что никаких ошибок не плюёт. Все токены сделаны на мои аккаунты, лимитов не заполнены. 

Может я что-то не понимаю и функции нейросети как-то по другому активируются? После python main.py включается джарвис и доступны только кастомки, на любые другие запросы джарвис просто говорит что команда не распознана

**Comment by harchock** [comment]
> мент в том, чт

сейчас столкнулся с точно такой же проблемой
пробую исправить

**Comment by Priler** [comment]
> > Возможно не прописаны API ключи или взяты чьи-то ключи (с достигнутым лимитом). Предоставь текст ошибки.
> 
> Весь момент в том, что никаких ошибок не плюёт. Все токены сделаны на мои аккаунты, лимитов не заполнены.
> 
> Может я что-то не понимаю и функции нейросети как-то по другому активируются? После python main.py включается джарвис и доступны только кастомки, на любые другие запросы джарвис просто говорит что команда не распознана

ChatGPT работает сейчас только через фразу "скажи <что-то>".
Всё остальное Джарвис пытается распознать как команду.
