### ISSUE TITLE
Не понимаю почему ошибка

### ISSUE THREAD

**Issue by iia3uk** [Priler/jarvis#26]
Using cache found in C:\Users\Papuaz/.cache\torch\hub\snakers4_silero-models_master
Traceback (most recent call last):
  File "C:\Users\Papuaz\Desktop\jarvis-master\main.py", line 44, in <module>
    porcupine = pvporcupine.create(
  File "C:\Python311\Lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Python311\Lib\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineInvalidArgumentError

Все либы стоят из requirements.txt

Добавил в dev.env токены: **** - закрыл символы у гпт 
PICOVOICE_TOKEN=<ZUwNw7oKqjqf9qQhhD59COtrcCalrkRngqwuIEoKHm7dXQ1yhEs+oA==>
OPENAI_TOKEN=<sk-6Q1qtv71tB5Bb1EGtuh5T3BlbkFJc1qsDpk82qLWG7z2****>

**Comment by iia3uk** [comment]
![image](https://user-images.githubusercontent.com/82707936/233208437-b743761e-6cca-4c84-9395-cebdbdd30b6b.png)
Беру токен на PICOVOICE тут - т.к. ссылки на сайт откуда брать нету, я не уверен что то-что нужно

**Comment by iia3uk** [comment]
Версия питона если зависит то.. у меня 3.11

**Comment by darkerck** [comment]
вместо <> попробуй ' или "

**Comment by Kanorto** [comment]
Там вообще не нужны скобки. Абсолютно без них. Но эта проблема не из-за токена, другие иссуе посмотри

**Comment by harchock** [comment]
> Using cache found in C:\Users\Papuaz/.cache\torch\hub\snakers4_silero-models_master Traceback (most recent call last): File "C:\Users\Papuaz\Desktop\jarvis-master\main.py", line 44, in porcupine = pvporcupine.create( File "C:\Python311\Lib\site-packages\pvporcupine_factory.py", line 69, in create return Porcupine( File "C:\Python311\Lib\site-packages\pvporcupine_porcupine.py", line 164, in **init** raise self._PICOVOICE_STATUS_TO_EXCEPTIONstatus pvporcupine._porcupine.PorcupineInvalidArgumentError
> 
> Все либы стоят из requirements.txt
> 
> Добавил в dev.env токены: **** - закрыл символы у гпт PICOVOICE_TOKEN=<ZUwNw7oKqjqf9qQhhD59COtrcCalrkRngqwuIEoKHm7dXQ1yhEs+oA==> OPENAI_TOKEN=<sk-6Q1qtv71tB5Bb1EGtuh5T3BlbkFJc1qsDpk82qLWG7z2****>

сейчас с самим плагином проблема, такое у многих сейчас
мы уже писали на гитхабе создателей и они сказали что активно начали исправлять эту ошибку

**Comment by neneton** [comment]
> > Using cache found in C:\Users\Papuaz/.cache\torch\hub\snakers4_silero-models_master Traceback (most recent call last): File "C:\Users\Papuaz\Desktop\jarvis-master\main.py", line 44, in porcupine = pvporcupine.create( File "C:\Python311\Lib\site-packages\pvporcupine_factory.py", line 69, in create return Porcupine( File "C:\Python311\Lib\site-packages\pvporcupine_porcupine.py", line 164, in **init** raise self._PICOVOICE_STATUS_TO_EXCEPTIONstatus pvporcupine._porcupine.PorcupineInvalidArgumentError
> > Все либы стоят из requirements.txt
> > Добавил в dev.env токены: **** - закрыл символы у гпт PICOVOICE_TOKEN=<ZUwNw7oKqjqf9qQhhD59COtrcCalrkRngqwuIEoKHm7dXQ1yhEs+oA==> OPENAI_TOKEN=<sk-6Q1qtv71tB5Bb1EGtuh5T3BlbkFJc1qsDpk82qLWG7z2****>
> 
> сейчас с самим плагином проблема, такое у многих сейчас мы уже писали на гитхабе создателей и они сказали что активно начали исправлять эту ошибку

а можно гит создателей, или временные рамки, когда фикс будет?)

**Comment by harchock** [comment]
> > > Using cache found in C:\Users\Papuaz/.cache\torch\hub\snakers4_silero-models_master Traceback (most recent call last): File "C:\Users\Papuaz\Desktop\jarvis-master\main.py", line 44, in porcupine = pvporcupine.create( File "C:\Python311\Lib\site-packages\pvporcupine_factory.py", line 69, in create return Porcupine( File "C:\Python311\Lib\site-packages\pvporcupine_porcupine.py", line 164, in **init** raise self._PICOVOICE_STATUS_TO_EXCEPTIONstatus pvporcupine._porcupine.PorcupineInvalidArgumentError
> > > Все либы стоят из requirements.txt
> > > Добавил в dev.env токены: **** - закрыл символы у гпт PICOVOICE_TOKEN=<ZUwNw7oKqjqf9qQhhD59COtrcCalrkRngqwuIEoKHm7dXQ1yhEs+oA==> OPENAI_TOKEN=<sk-6Q1qtv71tB5Bb1EGtuh5T3BlbkFJc1qsDpk82qLWG7z2****>
> > 
> > 
> > сейчас с самим плагином проблема, такое у многих сейчас мы уже писали на гитхабе создателей и они сказали что активно начали исправлять эту ошибку
> 
> а можно гит создателей, или временные рамки, когда фикс будет?)

временных рамок нету
https://github.com/Picovoice/porcupine

**Comment by harchock** [comment]
в проблеммах смотри, там 11 коментов

**Comment by neneton** [comment]
> в проблеммах смотри, там 11 коментов

спасибо)

**Comment by Priler** [comment]
@Kanorto @harchock Good job!)
Этот топик будет закрыт, как только подвезут фиксы в оф. репо.

**Comment by Kanorto** [comment]
@Priler а что нам делать до той поры? Разработчики могут это пофиксить не сразу. Есть ли обходные пути?
