### ISSUE TITLE
ошибка в ии для префикса

### ISSUE THREAD

**Issue by neneton** [Priler/jarvis#29]
Traceback (most recent call last):
  File "C:\Users\Артём\Desktop\2_0main_ai.py", line 714, in <module>
    porcupine = pvporcupine.create(
  File "C:\Users\Артём\.conda\envs\GENA\lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Users\Артём\.conda\envs\GENA\lib\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineIOError

токен есть, правда указан вот так access_key="access_key" (просто строка)
в чём может быть ошибка?

**Comment by otofarings** [comment]
> токен есть, правда указан вот так access_key="access_key" (просто строка)
> 
> в чём может быть ошибка?

Попробуй в своем файле .env указать access_key без кавычек:
access_key=**access_key**

**Comment by neneton** [comment]
> > токен есть, правда указан вот так access_key="access_key" (просто строка)
> > в чём может быть ошибка?
> 
> Попробуй в своем файле .env указать access_key без кавычек: access_key=**access_key**

не, я его указываю как переменную, .env файл не использую

**Comment by Priler** [comment]
Дубликат.
https://github.com/Priler/jarvis/issues/26
