### ISSUE TITLE
не понятно

### ISSUE THREAD

**Issue by ww123rov** [Priler/jarvis#3]
Я не могу понять как его запустит и скачать

**Comment by Vovo4k** [comment]
жиза

**Comment by HenryTownshand** [comment]
1. Качаете и устанавливаете Python 3.8.3. Так же качаем и закидываем в папку джарвиса это [https://download.lfd.uci.edu/pythonlibs/archived/PyAudio-0.2.11-cp38-cp38-win_amd64.whl](url)
2. Открываете cmd.exe и пишете в нём
`cd /D <путь к папке джарвиса>`
`pip install -r requirements.txt`
3. В config.py меняем OPENAI_TOKEN и если надо CHROME_PATH.
4. Опять открываем cmd.exe и пишем в нём
`cd /D <путь к папке джарвиса>`
`python main.py`
5. Смотрим какой микро у вас используется. Если в консоли правильно указано, то готово, если нет то меняем MICROPHONE_INDEX в config.py.

Готово)))))

**Comment by Kanorto** [comment]
не, нифига
