### ISSUE TITLE
проблема с simpleaudio

### ISSUE THREAD

**Issue by xtrysa** [Priler/jarvis#30]
пожалуйста помогите проблема с simpleaudio 
![2023-04-21_23-01-02](https://user-images.githubusercontent.com/131479546/233693677-4d69f3b1-2b76-49ab-97ec-d726d8cc7879.png)

**Comment by RoldexX** [comment]
Переходишь по ссылке в конце ошибки https://visualstudio.microsoft.com/ru/visual-cpp-build-tools/ и качаешь build tools. Далее устанавливаешь VS installer и уже в нем допом качаешь C++ (+-7гб). Это собственно всё, опять в терминале прописываешь pip install simpleaudio и вуаля.

Взял из ответа здесь: https://qna.habr.com/q/1271776

**Comment by Priler** [comment]
Можно просто поставить прекомпайлед для винды.
Скачать `.whl` можно отсюда - https://www.lfd.uci.edu/~gohlke/pythonlibs/#simpleaudio
Либо ставить через инструмент [pip-Win](https://pypi.org/project/pip-Win/).
