### ISSUE TITLE
OSError: [WinError 6] Неверный дескриптор 

### ISSUE THREAD

**Issue by Parazitka964** [Priler/jarvis#31]
Проделал все что нужно, установил все библиотеки/модули, сравнил их через команду pip list с файлом "requirements" , при запуске main.py в Visual Studio Code выдает OSError: [WinError 6] Неверный дескриптор (см скрин) и указывает на два файла, а именно : D:\jarvis-master\tts.py и D:\jarvis-master\main.py  файлы находятся именно по этому пути, файлы не повреждены, не заблокированы, доступ к ним есть. Возможно не нужно было запускать его в VS , подумал я, попробовал запустить джарвис через PowerShell от имени администратора, вошел в директорию , ввел python main.py проходит секунд 5 и PowerShell возвращается к этой же команде (см скрин) Windows 11 Pro 22H2 22621.1555 
![image](https://user-images.githubusercontent.com/64980448/233714117-a99da1c7-072a-47e7-8539-a50973b3ebd9.png)
![image](https://user-images.githubusercontent.com/64980448/233714325-1540ff56-16d5-4593-9f58-0a76c49e0df8.png)

**Comment by Priler** [comment]
Проверь версию Python, код тестировался только на версии `Python 3.8.3`.
Также попробуй запустить через `venv`.
Если не поможет, - почисти кэш Silero.
Еще вариант запустить код с CMD от имени администратора.

Воспроизвести ошибку не получается, так что вариантов почему так происходит может быть много.

**Comment by Kanorto** [comment]
все равно если папка даты твоего юзера называется по русски то есть проблемы. Пожалуйста, воспользуйся [этим гайдом](https://github.com/Priler/jarvis/issues/14#issuecomment-1510380432)

**Comment by Parazitka964** [comment]
> Проделал все что нужно, установил все библиотеки/модули, сравнил их через команду pip list с файлом "requirements" , при запуске main.py в Visual Studio Code выдает OSError: [WinError 6] Неверный дескриптор (см скрин) и указывает на два файла, а именно : D:\jarvis-master\tts.py и D:\jarvis-master\main.py файлы находятся именно по этому пути, файлы не повреждены, не заблокированы, доступ к ним есть. Возможно не нужно было запускать его в VS , подумал я, попробовал запустить джарвис через PowerShell от имени администратора, вошел в директорию , ввел python main.py проходит секунд 5 и PowerShell возвращается к этой же команде (см скрин) Windows 11 Pro 22H2 22621.1555 ![image](https://user-images.githubusercontent.com/64980448/233714117-a99da1c7-072a-47e7-8539-a50973b3ebd9.png) ![image](https://user-images.githubusercontent.com/64980448/233714325-1540ff56-16d5-4593-9f58-0a76c49e0df8.png)

**Comment by BlackCatDevel0per** [comment]
Используйте модуль multiprocess (форк multiprocessing) с расширеной сериализацией при помощи dill (аналог pickle)

Недавно ковырялся с одной старой прогой которую переписывать было не охота, а чтоб работало надо)
Вкратце: По некоторым причинам я не мог использовать requests, и использовал urllib3 который для чего-то использует RLock из threading который не сериализуется pickle-ом.. По итогу всё работает, и надеюсь к винде я ещё очень долго не вернусь XD
