### ISSUE TITLE
Overflow - reader is not reading fast enough.

### ISSUE THREAD

**Issue by Vizer560** [Priler/jarvis#33]
так и должно быть?
![image](https://user-images.githubusercontent.com/56556386/233771421-cd7f6e02-7a39-4f9e-8062-39d985c841d6.png)

**Comment by nikolay59088** [comment]
https://github.com/Priler/jarvis/issues/32

**Comment by Vizer560** [comment]
> #32

не помогло

**Comment by WindEger** [comment]
Он в этот момент грузит какое либо действие. Чаще всего возникает, когда скрипт не правильно выполняется. После какого момента у тебя возникло?

**Comment by WindEger** [comment]
Если что скрипты, которые в папке кастомные большинство надо переписывать. Если нужны рабочие на яндекс музыку установленную через Microsoft Store, могу скинуть.

**Comment by Priler** [comment]
Это не ошибка.
Если мешает - можно исправить многопоточностью.

**Comment by Kanorto** [comment]
> Если что скрипты, которые в папке кастомные большинство надо переписывать. Если нужны рабочие на яндекс музыку установленную через Microsoft Store, могу скинуть.

Можешь покидать пожалуйста. Только не exe.

**Comment by WindEger** [comment]
[1.zip](https://github.com/Priler/jarvis/files/11310278/1.zip)

это для яндекс музыки из майкрософт стора
