### ISSUE TITLE
не понимаю в чем ошибка, OPENAI_TOKEN и PICOVOICE_TOKEN ввел

### ISSUE THREAD

**Issue by xtrysa** [Priler/jarvis#34]
что делать? не знаю в чем дело
![2023-04-23](https://user-images.githubusercontent.com/131479546/233846476-55145046-0ca3-4b6c-b9b3-26507c8580be.png)

**Comment by harchock** [comment]
> что делать? не знаю в чем дело ![2023-04-23](https://user-images.githubusercontent.com/131479546/233846476-55145046-0ca3-4b6c-b9b3-26507c8580be.png)

я сам столкнулся с этой проблемой
но я уже нашёл решение
напиши мне в тг @m_ll_n_r
я тебе скину код который просто вставь и замень в нужном месте на свой апи
но с чатгпт я проблему не решил ещё
он просто вылетает когда задаешь вопрос ему в чатгпт

**Comment by xtrysa** [comment]
> Я знаю как тебе можно помочь. Зайди в файл dev.env и где ты вставлял ключи замени знаки с _**<**_ и _**>**_, на 
![2023-04-24_21-24-46](https://user-images.githubusercontent.com/131479546/234043759-a06087a8-fd0e-481b-910e-840c72e2c249.png)
_**""**_ и тогда все заработает, это из-за того что он не понимает данные в переменных, а поменяв знаки, ты переменные превратишь в переменные с текстом и тогда все заработает. Мне это помогло и тебе должно, так как в консоли дебагер просит указать ключи в значение string.

**Comment by xtrysa** [comment]
> Я знаю как тебе можно помочь. Зайди в файл dev.env и где ты вставлял ключи замени знаки с _**<**_ и _**>**_, на _**""**_ и тогда все заработает, это из-за того что он не понимает данные в переменных, а поменяв знаки, ты переменные превратишь в переменные с текстом и тогда все заработает. Мне это помогло и тебе должно, так как в консоли дебагер просит указать ключи в значение string.

спасибо, но у меня почему то не работает
