### ISSUE TITLE
как сделать, чтобы работал диалог с Джарвисом?

### ISSUE THREAD

**Issue by Lolleds** [Priler/jarvis#39]

**Comment by Lolleds** [comment]
и ещё проблемы с доступном не могу настроить
![image](https://user-images.githubusercontent.com/131714589/234111231-c96f88f2-38a0-4805-8f21-1a645d6af795.png)

**Comment by harchock** [comment]
> и ещё проблемы с доступном не могу настроить ![image](https://user-images.githubusercontent.com/131714589/234111231-c96f88f2-38a0-4805-8f21-1a645d6af795.png)

он говорил если нужно поменять путь в гуглу, но так же это нужно делать в ахк скрипте и перевести его в ехе
