### ISSUE TITLE
Для идиотов которые не могут установить 'requirements.txt' руками.

### ISSUE THREAD

**Issue by BSNIKYT** [Priler/jarvis#4]
discordpy
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
antlr4-python3-runtime==4.8
anyio==3.6.2
asttokens==2.0.5
async-generator==1.10
async-timeout==4.0.2
attrs==22.2.0
backcall==0.2.0
backports.zoneinfo==0.2.1
beautifulsoup4==4.11.1
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
colorama==0.4.4
comtypes==1.1.14
decorator==5.1.1
docopt==0.6.2
exceptiongroup==1.1.1
executing==0.8.3
frozenlist==1.3.3
fuzzywuzzy==0.18.0
gpytranslate==1.5.1
h11==0.14.0
httpcore==0.17.0
httpx==0.24.0
humanize==4.1.0
idna==3.3
ipython==8.3.0
jedi==0.18.1
Js2Py==0.71
keyboard==0.13.5
markdown-it-py==2.2.0
matplotlib-inline==0.1.3
mdurl==0.1.2
multidict==6.0.4
num2t4ru
numpy==1.22.3
omegaconf==2.1.2
openai==0.27.4
outcome==1.2.0
packaging==21.3
parso==0.8.3
pickleshare==0.7.5
picovoice==2.1.5
pipwin==0.5.2
playsound==1.3.0
prompt-toolkit==3.0.29
psutil==5.9.4
pure-eval==0.2.2
pvporcupine==2.1.4
pvrecorder==1.1.1
pvrhino==2.1.7
PyAudio 
pycaw==20230407
pycparser==2.21
Pygments==2.12.0
pyjsparser==2.7.1
pyparsing==3.0.9
PyPrind==2.11.3
pySmartDL==1.3.4
PySocks==1.7.1
python-Levenshtein==0.12.2
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
requests==2.27.1
rich==13.3.2
selenium==4.8.3
silero==0.1.0
simpleaudio==1.0.4
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
sounddevice==0.4.4
SoundFile==0.10.3.post1
soupsieve==2.3.2.post1
SpeechRecognition==3.8.1
stack-data==0.2.0
torch==1.10.0
torchaudio==0.10.0
tqdm==4.65.0
traitlets==5.2.0
trio==0.22.0
trio-websocket==0.10.2
typing-extensions==4.2.0
tzdata==2022.1
tzlocal==4.2
urllib3==1.26.9
vosk==0.3.32
wcwidth==0.2.5
wsproto==1.2.0
yarl==1.8.2

Берете и копируете этот текст в замен того что было и вставляете его в 'requirements.txt'.
P. S. в 'requirements.txt' какая-то дичь с установкой происходит. (в консоли показывает русские символы, хотя их там нет)

import os
with open(r'requirements.txt', 'r') as f:
    for mod in f:os.system(rf"pip install {mod}")

**Comment by Kanorto** [comment]
ERROR: Could not find a version that satisfies the requirement num2t4ru (from versions: none)
ERROR: No matching distribution found for num2t4ru

**Comment by Kanorto** [comment]
со многими была такая же трабла, но тут я не знаю
запусщено от админки, пайтон точь в точь.

**Comment by nikolay59088** [comment]
> ERROR: Could not find a version that satisfies the requirement num2t4ru (from versions: none) ERROR: No matching distribution found for num2t4ru

pip install num2t4ru@git+https://github.com/seriyps/ru_number_to_text@3b9ccdb36bb744341ee7bec9c50b51198259c648

**Comment by Kanorto** [comment]
> Pygments

Pygments==2.13.0
иначе дает ошибку с версиями. 


`ERROR: Cannot install -r requirements.txt (line 30), Pygments==2.12.0 and rich==13.3.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Pygments==2.12.0
    ipython 8.3.0 depends on pygments>=2.4.0
    rich 13.3.2 depends on pygments<3.0.0 and >=2.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by Kanorto** [comment]
> pip install num2t4ru@git+https://github.com/seriyps/ru_number_to_text@3b9ccdb36bb744341ee7bec9c50b51198259c648

не работает. 

D:\JARVIS>pip install num2t4ru@git+https://github.com/seriyps/ru_number_to_text@3b9ccdb36bb744341ee7bec9c50b51198259c648
Collecting num2t4ru@ git+https://github.com/seriyps/ru_number_to_text@3b9ccdb36bb744341ee7bec9c50b51198259c648
  Using cached num2t4ru-2.0.0-py3-none-any.whl

а потом при установке Requrements снова ошибка
ERROR: Could not find a version that satisfies the requirement num2t4ru (from versions: none)
ERROR: No matching distribution found for num2t4ru

**Comment by nikolay59088** [comment]
> 

это потому что он пытается опять найти num2t4ru в офф репозиториях а его там нет, я просто после ручной установки убрал его из списка и после установки остальных зависимостей проверил, что num2t4ru установлен через pip list. После этого у меня джарвис спокойно запустился
