### ISSUE TITLE
не робит

### ISSUE THREAD

**Issue by FLASTI** [Priler/jarvis#40]
у меня есть кастам команда на передвижения мышки, когда говорю в лево и т.д. мышка движется в лево НО пока я не завершу ахк он не слышит следящее команды оно пишет [WARN] Overflow - reader is not reading fast enough.  ахк выглядит так:
loop {
MouseMove, 30, 0, 100, R
}
F1::Exitapp

**Comment by Kanorto** [comment]
как я понимаю ты биндишь клавишу на выход? насколько лево ты пытаешь делать что залупливаешь мув?
Это предупреждение указывает использование микрофона другим приложением. В данных реалиях это не фиксится.

**Comment by FLASTI** [comment]
> как я понимаю ты биндишь клавишу на выход? насколько лево ты пытаешь делать что залупливаешь мув? Это предупреждение указывает использование микрофона другим приложением. В данных реалиях это не фиксится.
мне нужно чтобы он бесконечно двигалось в лево право и т.д. пока не скажу стоп

**Comment by FLASTI** [comment]
> как я понимаю ты биндишь клавишу на выход? насколько лево ты пытаешь делать что залупливаешь мув? Это предупреждение указывает использование микрофона другим приложением. В данных реалиях это не фиксится.
мне нужно чтобы он бесконечно двигалось в лево право и тд пока не скажу стоп

**Comment by FLASTI** [comment]
> как я понимаю ты биндишь клавишу на выход? насколько лево ты пытаешь делать что залупливаешь мув? Это предупреждение указывает использование микрофона другим приложением. В данных реалиях это не фиксится.
