### ISSUE TITLE
при запуске закрывается 

### ISSUE THREAD

**Issue by invictus1902** [Priler/jarvis#72]
приложение при его открытии он начинает запуск и сразу закрывается  не успев открыть главное меню

**Comment by xor1c** [comment]
он просто ещё мои issues не пофиксил поэтому

**Comment by Kanorto** [comment]
> он просто ещё мои issues не пофиксил поэтому

Я не вижу твоего топика. Пожалуйста не спам больше, ведь тебе могут отказать в поддержке и заблокировать

**Comment by xor1c** [comment]
> > он просто ещё мои issues не пофиксил поэтому
> 
> Я не вижу твоего топика. Пожалуйста не спам больше, ведь тебе могут отказать в поддержке и заблокировать

я понял))

**Comment by Kanorto** [comment]
Доброго дня. Пожалуйста, проверьте чтобы у вас была установлена последняя версия со всеми фиксами.
