### ISSUE TITLE
no work 

### ISSUE THREAD

**Issue by FangRazy** [Priler/jarvis#73]
![Скриншот 26-04-2023 231715](https://user-images.githubusercontent.com/86495486/234692794-711e8001-0d1c-498b-823d-e80cc6eba9b4.jpg)

**Comment by Kanorto** [comment]
После этого программа вылетает, или понимает вашу речь. Также необходимо больше данных о среде запуска и т.п.

**Comment by FangRazy** [comment]
win 11

**Comment by Vuiiuj** [comment]
Джарвис запускается говорит доброе утро и все меня не слышит 
![Снимок экрана (7)](https://user-images.githubusercontent.com/51422965/234870369-4d7edde7-132c-449a-8706-c9a3bf2c9d37.png)

**Comment by Kanorto** [comment]
> win 11

вы не даете никаких данных. Расскажите что у вас происходит, например: не запускается интерфейс, что-то другое. Также укажите больше системных характеристик, и т.д.

**Comment by Vuiiuj** [comment]
Это не мой вопрос)

пт, 28 апр. 2023 г. в 15:14, Kanorto ***@***.***>:
