### ISSUE TITLE
Turns the program off immediately

### ISSUE THREAD

**Issue by BrIruka** [Priler/jarvis#74]
https://youtu.be/Jt725AtarU8

**Comment by Kanorto** [comment]
Если это возможно, запустите ваш файл с помощью батника, в котором в конце на следующей строке после строки запуска будет указано `pause` . После этого скопируйте логи консоли, и вставьте сюда. Мы постараемся помочь

**Comment by Priler** [comment]
Недостаточно информации.
Возможно исправлено в 0.0.3.
Если не заработает, - переоткрой и прикрепи логи.
