### ISSUE TITLE
Ошибка при установке simpleaudio

### ISSUE THREAD

**Issue by dmitrijkv** [Priler/jarvis#75]
Дмитрий Квитко:
Collecting simpleaudio
  Using cached simpleaudio-1.0.4.tar.gz (2.0 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: simpleaudio
  Building wheel for simpleaudio (pyproject.toml): started
  Building wheel for simpleaudio (pyproject.toml): finished with status 'error'
Failed to build simpleaudio

  error: subprocess-exited-with-error
  
  Building wheel for simpleaudio (pyproject.toml) did not run successfully.
  exit code: 1
  
  [18 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\simpleaudio
  copying simpleaudio\__init__.py -> build\lib.win-amd64-cpython-311\simpleaudio
  copying simpleaudio\shiny.py -> build\lib.win-amd64-cpython-311\simpleaudio
  copying simpleaudio\functionchecks.py -> build\lib.win-amd64-cpython-311\simpleaudio
  creating build\lib.win-amd64-cpython-311\simpleaudio\test_audio
  copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-cpython-311\simpleaudio\test_audio
  copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-cpython-311\simpleaudio\test_audio
  copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-cpython-311\simpleaudio\test_audio
  copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-cpython-311\simpleaudio\test_audio
  copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-cpython-311\simpleaudio\test_audio
  running build_ext
  building 'simpleaudio._simpleaudio' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simpleaudio
ERROR: Could not build wheels for simpleaudio, which is required to install pyproject.toml-based projects

"Microsoft C++ Build Tools" установлен, последняя версия.

**Comment by borusikk** [comment]
Ошибка связана с тем, что у вас отсутствует необходимый компонент для сборки библиотеки simpleaudio. Как указано в выводе ошибки, требуется Microsoft Visual C++ 14.0 или более поздняя версия.

Вы можете загрузить Microsoft Visual C++ Build Tools, чтобы установить необходимые компоненты сборки. Следуйте инструкциям в ссылке, предоставленной в ошибке, чтобы загрузить и установить этот компонент.

После установки Microsoft Visual C++ Build Tools попробуйте установить библиотеку simpleaudio еще раз, используя команду pip install simpleaudio.

**Comment by dmitrijkv** [comment]
Я умею переводить.
На самом деле прошла ошибка после того как python 3.8.3 поставил.

**Comment by Priler** [comment]
Не связано с актуальной версией.
