### ISSUE TITLE
После команды "Открой YouTube" появилось ошибка

### ISSUE THREAD

**Issue by sanjarbarakayev** [Priler/jarvis#77]
![image](https://user-images.githubusercontent.com/64146515/234975112-a659a8e1-6a61-413b-92b8-cdf46f973512.png)

**Comment by Invader001** [comment]
У тебя браузер не в заданной директории. Либо установи Хром в эту локацию, либо меняй локацию браузера в коде комманд Джарвиса.

**Comment by Priler** [comment]
Ошибка известна.
Исправим в ближайшем обновлении.

**Comment by Priler** [comment]
Дубликат.
https://github.com/Priler/jarvis/issues/78
