### ISSUE TITLE
Porcupine error: either API key is not valid or there is no internet connection

### ISSUE THREAD

**Issue by Kanorto** [Priler/jarvis#80]
Добрый день. Взял токен с официального сайта, вставил в конфиг, но ничего. Приложение так и продолжает 
![image](https://user-images.githubusercontent.com/77388225/235145510-ccf88b10-f91e-4c4e-8933-412a9db22b71.png)
Консоль: 
![image](https://user-images.githubusercontent.com/77388225/235145603-7404c930-dff8-4dd3-879f-0263f10c3a3c.png)
Апи ключ взят с их сайта скопирован и вставлен верно.

**Comment by Liremant** [comment]
Такая же проблема.Думаю что-то с апишником,либо  хауди криво прописал считывание апи пиковоиса(?)

**Comment by Kanorto** [comment]
скорее всего проблема с некоторыми виндовыми клиентами. Ранее была подобная ошибка, видимо это затронуло и rust SDK.

**Comment by Priler** [comment]
Ошибка известна и нам, и разработчикам Picovoice.
Над решением уже работаем.

**Comment by Priler** [comment]
Исправлено в версии 0.0.3 (интегрирован патч от разработчиков).

**Comment by Kanorto** [comment]
> Исправлено в версии 0.0.3 (интегрирован патч от разработчиков).

А где версия 0.0.3?
