### ISSUE TITLE
Проблема первого билда 

### ISSUE THREAD

**Issue by MOTifoYe** [Priler/jarvis#81]
После клонирования репозитория и установки зависимостей, первый билд собрать просто не получается. 

Ошибку вызывает строка [`import { routes } from "../.routify/routes";`](https://github.com/Priler/jarvis/blob/4e1413d400a3883c391a95c2eaa1dd9e5a45ccb0/src/App.svelte#L4)

В Readme указаны команды билда и запуска, но они не работают из-за отсутствия ".routify/routes". В файле .gitignore указано не заливать эту папку. 

Нужно ли как-то инициализировать зависимости проекта или сам проект перед сборкой? 

Можно, конечно, собрать проект, закомментировав строки:
[`import { routes } from "../.routify/routes";`](https://github.com/Priler/jarvis/blob/4e1413d400a3883c391a95c2eaa1dd9e5a45ccb0/src/App.svelte#L4)
[`<Router {routes} />`](https://github.com/Priler/jarvis/blob/4e1413d400a3883c391a95c2eaa1dd9e5a45ccb0/src/App.svelte#L16)
Тогда появится этот заветный каталог ".routify"

**Comment by Priler** [comment]
Директория `.routify` не просто так указано в `.gitignore`, так как она требуется только локально при разработке и заливать её в ГХ смысла нет.
Routify это [роутер для Svelte](https://www.routify.dev/).

Попробуй команду `npm i -D @roxi/routify npm-run-all`.
Возможно я забыл отредачить депсы.
Оно по идее само должно подтягиваться.
