### ISSUE TITLE
В данный момент ассистент не прослушивает команды.

### ISSUE THREAD

**Issue by Kurskikh** [Priler/jarvis#86]
Привет! Настроил приложение, но в главном окне:
Внимание!
В данный момент ассистент не прослушивает команды.
Пожалуйста, [перейдите в настройки](https://tauri.localhost/settings) и введите ключ Picovoice.

Ключ указан, но ничего не меняется(

**Comment by Kanorto** [comment]
Добрый день. Данная проблема известна всем. Вы можете установить subscribe(подписаться на уведомления) на  https://github.com/Priler/jarvis/issues/80 и https://github.com/Priler/jarvis/issues/26. Просьба закрыть дополнительный issue, и следить за теми.

**Comment by ImanbekJ** [comment]
Была такая же проблема устранил путем разрешения к микрофону всем  приложением. Это будет как то так Параметры-Конфиденциальность-Микрофон-Разрешить приложением доступ к микрофону. Это на  винде 10 по крайней мери у меня это сработало и Джарвис работает . Отпишитесь если помог)

**Comment by ImanbekJ** [comment]
> Привет! Настроил приложение, но в главном окне: Внимание! В данный момент ассистент не прослушивает команду. Пожалуйста, [выберите](https://tauri.localhost/settings) ключ Picovoice.
> 
> Ключ указан, но ничего не меняется(

Была такая же проблема, как устранил разрешение к микрофонному приложению всем. Параметры-Конфиденциальность-Микрофон-Разрешить доступ приложения к микрофону. Это на винде 10 по крайней мери у меня это сработало и Джарвис работает . Отпишитесь, если помог)

**Comment by Kurskikh** [comment]
Привет! не помогло(( Висит такая же плашка

**Comment by Kurskikh** [comment]
https://github.com/Priler/jarvis/issues/80 и https://github.com/Priler/jarvis/issues/26
