### ISSUE TITLE
Где хранится Голос ассистента

### ISSUE THREAD

**Issue by Dippery** [Priler/jarvis#88]
Как я могу добавить в приложение свою озвучку, со своим названием, без замен озвучки Хауди или из фильма? 
Надеюсь я понятно выразил свой вопрос)

**Comment by ljisrfpjkofgsd** [comment]
В папке sound. Если дело идет именно что о  пере озвучке то заходи папку commands посмотри при каких условиях что он отвечает (к примеру на запуск стима он выбирает одно из названий на рандом и включает звук вод этим именем) и заменяй саунды по смыслу, делая им такие же имена.
![A_nR9BSiI1c](https://github.com/Priler/jarvis/assets/133608349/c4629e67-6210-4e3c-bd8e-8616b712f1ea)

**Comment by Priler** [comment]
Пока что голоса статично хранятся в папке src-tauri/sound (с версии 0.0.3 в папке app/sound).
