### ISSUE TITLE
Активационная фраза 

### ISSUE THREAD

**Issue by Mr-X-01** [Priler/jarvis#91]
Здравствуйте, я хотел поменять данный ассистент под себя чтоб пользоваться но я никак не могу ему поменять имя и активационную фразу. где и как я могу его поменять?

**Comment by SupremrKing** [comment]
Так же интересует данный вопрос. Не могу разобраться как именно изменить активационную фразу. Буду рад узнать.

**Comment by Mr-X-01** [comment]
Здравствуйте, я узнал как это сделать могу как нибудь потихоньку рассказать
мой тг @bunny_not_found

сб, 20 мая 2023 г., 23:34 SupremrKing ***@***.***>:

**Comment by Priler** [comment]
Пока что активационная фраза никак не изменяется.
Такая возможность будет в будущих версиях.
